[2025-04-13T17:46:02.205+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_search_volume_aggregation.aggregate_search_volume scheduled__2025-04-13T16:00:00+00:00 [queued]>
[2025-04-13T17:46:02.211+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_search_volume_aggregation.aggregate_search_volume scheduled__2025-04-13T16:00:00+00:00 [queued]>
[2025-04-13T17:46:02.212+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 3
[2025-04-13T17:46:02.221+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): aggregate_search_volume> on 2025-04-13 16:00:00+00:00
[2025-04-13T17:46:02.226+0000] {standard_task_runner.py:57} INFO - Started process 189 to run task
[2025-04-13T17:46:02.229+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'daily_search_volume_aggregation', 'aggregate_search_volume', 'scheduled__2025-04-13T16:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/daily_search_volume_aggregation.py', '--cfg-path', '/tmp/tmptccohyso']
[2025-04-13T17:46:02.232+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask aggregate_search_volume
[2025-04-13T17:46:02.302+0000] {task_command.py:415} INFO - Running <TaskInstance: daily_search_volume_aggregation.aggregate_search_volume scheduled__2025-04-13T16:00:00+00:00 [running]> on host 8c7412a2cf7e
[2025-04-13T17:46:02.376+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='daily_search_volume_aggregation' AIRFLOW_CTX_TASK_ID='aggregate_search_volume' AIRFLOW_CTX_EXECUTION_DATE='2025-04-13T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-13T16:00:00+00:00'
[2025-04-13T17:46:02.391+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2025-04-13T17:46:02.392+0000] {spark_submit.py:340} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.master=local[*] --conf spark.app.name=daily_search_volume_aggregation --conf spark.driver.memory=1g --conf spark.executor.memory=1g --name arrow-spark --queue root.default /opt/airflow/dags/spark/daily_aggregation.py
[2025-04-13T17:46:02.475+0000] {spark_submit.py:491} INFO - /home/airflow/.local/lib/python3.8/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-04-13T17:46:02.476+0000] {spark_submit.py:491} INFO - JAVA_HOME is not set
[2025-04-13T17:46:02.486+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 156, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.master=local[*] --conf spark.app.name=daily_search_volume_aggregation --conf spark.driver.memory=1g --conf spark.executor.memory=1g --name arrow-spark --queue root.default /opt/airflow/dags/spark/daily_aggregation.py. Error code is: 1.
[2025-04-13T17:46:02.495+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_search_volume_aggregation, task_id=aggregate_search_volume, execution_date=20250413T160000, start_date=20250413T174602, end_date=20250413T174602
[2025-04-13T17:46:02.501+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task aggregate_search_volume (Cannot execute: spark-submit --master yarn --conf spark.master=local[*] --conf spark.app.name=daily_search_volume_aggregation --conf spark.driver.memory=1g --conf spark.executor.memory=1g --name arrow-spark --queue root.default /opt/airflow/dags/spark/daily_aggregation.py. Error code is: 1.; 189)
[2025-04-13T17:46:02.538+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-04-13T17:46:02.550+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
